# Generated by Django 5.1.3 on 2024-12-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "cep",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("logradouro", models.CharField(max_length=255)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
            ],
        ),
    ]
