# Generated by Django 5.1.3 on 2024-12-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bairros", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endereco",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="estado",
        ),
        migrations.AddField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="endereco",
            name="numero",
            field=models.CharField(default="s/n", max_length=15),
        ),
        migrations.AddField(
            model_name="endereco",
            name="observacao",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
