# Generated by Django 5.1.3 on 2024-12-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bairros", "0002_remove_endereco_cidade_remove_endereco_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endereco",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="endereco",
            name="cep",
            field=models.CharField(max_length=10),
        ),
    ]
