# Generated by Django 5.1.3 on 2024-11-08 23:36

from django.apps.registry import Apps
from django.db import migrations

NOME_ADMIN = 'Admin'
NOME_SERVIDOR = 'Servidor'
NOME_VISITANTE = 'Visitante'

def cria_user_groups(apps: Apps):
    Group = apps.get_model('auth', 'Group')

    Group.objects.create(name=NOME_ADMIN)
    Group.objects.create(name=NOME_SERVIDOR)
    Group.objects.create(name=NOME_VISITANTE)

def remove_user_groups(apps: Apps):
    Group = apps.get_model('auth', 'Group')

    Group.objects.filter(name=NOME_ADMIN).delete()
    Group.objects.filter(name=NOME_SERVIDOR).delete()
    Group.objects.filter(name=NOME_VISITANTE).delete()



class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(cria_user_groups, remove_user_groups)
    ]
