# Generated by Django 5.1.3 on 2024-12-03 02:42

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14),
        ),
    ]
