# Generated by Django 5.1.3 on 2024-12-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnico",
            name="matricula",
            field=models.CharField(max_length=100),
        ),
    ]
