# Generated by Django 5.1.3 on 2024-12-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="pareceres/imagens/")),
            ],
        ),
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="pareceres/imagens/")),
            ],
        ),
        migrations.CreateModel(
            name="ParecerTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laudo", models.TextField(max_length=1000)),
                ("justificativa", models.TextField(max_length=1000)),
                ("recomendacao", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.TextField(max_length=200)),
                ("razao_solicitacao", models.TextField(max_length=1000)),
                ("indice_prioridade", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_ANALISE", "Em Análise"),
                            ("CANCELADO", "Cancelado"),
                            ("ENCERRADO", "Encerrado"),
                            ("ENCAMINHADO", "Encaminhado"),
                        ],
                        default="ABERTO",
                        max_length=30,
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True,
                        choices=[("SAUDAVEL", "Saudável"), ("DOENTE", "Doente")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("abertura", models.DateTimeField(auto_now_add=True)),
                ("ultima_modificacao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
