# Generated by Django 5.1.3 on 2024-12-03 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processos", "0001_initial"),
        ("usuarios", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parecertecnico",
            name="tecnico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="usuarios.tecnico"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processo_solicitante",
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="tecnico_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processo_responsavel",
                to="usuarios.tecnico",
            ),
        ),
        migrations.AddField(
            model_name="parecertecnico",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processos.processo"
            ),
        ),
        migrations.AddField(
            model_name="imagem",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processos.processo"
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processos.processo"
            ),
        ),
    ]
