# Generated by Django 5.1.3 on 2024-12-12 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0002_initial"),
        ("usuarios", "0003_alter_usuario_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parecertecnico",
            name="tecnico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="usuarios.tecnico",
            ),
        ),
    ]
