# Generated by Django 5.1.3 on 2024-12-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="endereco",
            field=models.CharField(max_length=200),
        ),
    ]
