# Generated by Django 5.1.3 on 2024-12-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0003_alter_parecertecnico_tecnico"),
        ("processos", "0003_alter_processo_endereco"),
    ]

    operations = []
