# Generated by Django 5.1.3 on 2024-12-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0004_merge_20241213_0010"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="imagem",
        ),
        migrations.AddField(
            model_name="documento",
            name="documento",
            field=models.ImageField(default="", upload_to="pareceres/documentos/"),
            preserve_default=False,
        ),
    ]
